author: Martin Irha <martin@tind.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

name: cron_wizard
version: 2.0.0

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  sass_builder: ^1.0.1

transformers:
- angular:
    entry_points:
    - lib/cron_wizard.dart
- sass_builder
